language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

addons:
  apt:
    packages:
    - libopenblas-dev
    - liblapack-dev
    - gfortran
    - imagemagick
    - python-numpy
    - python-scipy

before_install:
  - git clone https://github.com/contiki-os/contiki.git ~/
  - mkdir ~/Experiments
  - mkdir ~/Projects

install:
  - pip install -r requirements.txt

script:
  - fab test
