language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - sudo apt-get install gfortran libopenblas-dev liblapack-dev
  - sudo apt-get install -qq python-numpy python-scipy
  - sudo apt-get install imagemagick
  - cd ~
  - git clone https://github.com/contiki-os/contiki.git
  - mkdir ~/Experiments
  - mkdir ~/Projects
  - cd ~/Projects

install:
  - pip install -r requirements.txt

script:
  - fab test
