language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - travis_wait 30 pip install scipy
  - pip install -r requirements.txt
# command to run tests
script: "fab test"
