site_name: "RPL Attacks Framework - For simulating WSN with a malicious mote attacking RPL based on Contiki"
repo_url: https://github.com/dhondta/rpl-attacks
site_author: dhondta
docs_dir: doc
pages:
  - Introduction: intro.md
  - Installation: install.md
  - Usage: usage.md
  - Commands: commands.md
  - Campaigns: campaigns.md
  - Building Blocks: building-blocks.md
  - Reporting: report.md
extra:
  mailto: alexandre.dhondt@gmail.com
theme: readthedocs
use_directory_urls: false
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
requirements_file: 