---
- name: Install common libraries
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - ubuntu-desktop
    - build-essential
    - doxygen
    - gfortran
    - imagemagick

- name: Install Python stuffs
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - python-dev
    - python-pip

- name: Install Git
  apt:
    pkg: git
    state: latest
