---
- name: Install Tshark
  apt:
    pkg: tshark
    state: latest
    install_recommends: yes
    force: yes

- name: Install Python modules
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - python-numpy
    - python-scipy
    - python-tk
    - python-pexpect
