---
# Clone the git repositories
- name: Clone repository
  git:
    repo: "https://github.com/dhondta/rpl-attacks.git"
    dest: "{{ rplaf_root }}"
    force: yes
    recursive: no
    accept_hostkey: yes

# Change files mode
- name: Change main Python script's mode to executable
  file:
    dest: "{{ rplaf_root }}/main.py"
    mode: 0744

# Install the requirements
- name: Install Python requirements
  pip:
    requirements: "{{ rplaf_root }}/requirements.txt"

# Copy configuration file
- name: Copy configuration file
  template:
    src: .rpl-attacks.conf
    dest: "{{ item }}"
    owner: vagrant
  with_items:
    - /home/vagrant/
    - /root/

# Run project setup
- name: Setup RPL Attacks Framework
  expect:
    chdir: "{{ rplaf_root }}"
    command: fab setup
    responses:
      "Would you like to upgrade it now ? (yes|no) [default: no] ": "no"

# Test project
- name: Test RPL Attacks Framework
  command: fab test
  args:
    chdir: "{{ rplaf_root }}"
