---
# Clone the git repositories
- name: Clone repository
  git:
    repo: "https://github.com/contiki-os/contiki.git"
    dest: "{{ contiki_root }}"
    force: yes
    recursive: yes
    accept_hostkey: yes

# Change directory owner
- name: Change Contiki OS directory ownership
  file:
    dest: "{{ contiki_root }}"
    owner: vagrant
    group: vagrant
    mode: 0644
    recurse: yes
