---
- name: Create the RPL Attacks Framework appliance
  hosts: rpl-attacks-framework
  sudo: yes
  roles:
    - baseline
    - contiki-os
    - rpl-attacks
  vars:
    current_jdk: openjdk-8
    private_network: 192.168.27.0/24
    contiki_root: /opt/contiki
    rplaf_root: /opt/rpl-attacks
    keyboard_layout: be
